services:
  - type: web
    name: roxin-site
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --worker-class eventlet --worker-connections 1000 --timeout 300 --keepalive 5 --max-requests 1000 --max-requests-jitter 100 --preload
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.lgaybwinuhssjoyyyxkn:UNFtXoJfQsL5E1py@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /
    autoDeploy: true 